### ping server
GET localhost:8080/ping


### Get user by ID
GET localhost:8080/api/v1/users/4

### Get users by status
GET localhost:8080/api/v1/users/status/active

### Get all users
GET localhost:8080/api/v1/users

### create new user
POST localhost:8080/api/v1/users/
Content-Type: application/json

{
  "firstname": "Abdullah",
  "lastname": "'Mohammed'",
  "email": "abdul@nexus.com",
  "status": "pending"
}

### update user
PATCH localhost:8080/api/v1/users/22
Content-Type: application/json

{
  "status": "active"
}

### 13 15 17 18 19 21
### delete user
DELETE localhost:8080/api/v1/users/21
Content-Type: application/json